### ISSUE TITLE
TO-DO LIST

### ISSUE THREAD

**Issue by JohnMTorgerson** [Atelaes/Mynda#69]
**Bugs/Features Before Alpha release:**

- [ ] Performance work on mousing over rows
- [x] Performance work on adding videos to library
- [ ] Performance work on switching playlists
- [x] Auto-tagging
- [ ] Fix issue #68 (next/prev buttons)

**After Alpha release (features only):**

- [ ] re-order columns by DnD
- [ ] re-order playlists by DnD from tabs
- [ ] rename playlists from tab
- [ ] collapse/resize details pane
- [ ] playlist dropdown for non-tabbed playlists
